# rabbit connect url
url = "http://rabbit:15672/"
user = "user"
password = "user"

[[vhosts]]
  name = "/vhost1"
  [[vhosts.queue]]
    title = "queue1"
    warning = 1.2
    error = 1.5
  [[vhosts.queue]]
    title = "queue2"
    warning = 1.2
    error = 1.5


[[vhosts]]
  name = "/vhost2"
  [[vhosts.queue]]
    title = "queue1"
    warning = 0.7
    error = 1.0
  [[vhosts.queue]]
    title = "queue2"
    warning = 1.5
    error = 3.0
  [[vhosts.queue]]
      title = "queue3"
      warning = 1.5
      error = 2.0
  [[vhosts.queue]]
      title = "queue4"
      warning = 1.5
      error = 2.0

